server:
  port: 8080
  servlet:
    context-path: /match
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 102400000
mybatis:
  mapper-locations: classpath:mapping/*.xml
filemanage:
  #    urlpath: http://localhost:8080/match/
  #    savepath: D:\\web\\algorithm
  savepath: /usr/local/match/
  urlpath: http://192.168.254.128:8080/match/
logging:
  pattern:
    console: "%d-%msg%n"
    file: /home/targetLog/${spring.application.name}.log
  level:
    org.work.dao: DEBUG
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: wmmatch
  datasource:
    name: wmmatch_base
    url: jdbc:mysql://123.56.224.203:3306/wmmatch?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 151Dundi3hbhl@@#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 2
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 307200MB
      max-request-size: 307200MB
    jackson:
      date-format: yyyy-MM-dd HH:mm
      time-zone: GMT+8
    mvc:
      date-format: yyyy-MM-dd HH:mm
      favicon:
        enabled: true
      static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:${filemanage.savepath}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    converters:
      preferred-json-mapper: jackson